package ufrn.dimap.lets.ehmetrics.abstractmodel;

public enum HandlerActionType
{
	ECLIPSE_PRINTSTACKTRACE,
	INTELLIJ_PRINTSTACKTRACE,
	NETBEANS_LOGGER_LOG,
	
	IRRELEVANT,
	LOG,
	PRINTSTACKTRACE,
	SYSTEM_PRINT,
	CLOSE_RESOURCE,
	NOTIFY_USER,
	USE_VALUE,
	TERMINATE,
	UNKNOWN,
	RETURN_EMPTY,
	RETURN_VALUE,
	RETURN_NULL,
	RETHROW,
	THROW_NEW,
	WRAP_SAME,
	WRAP_CHECKED_CHECKED,
	WRAP_CHECKED_UNCHECKED,
	WRAP_CHECKED_ERROR,
	WRAP_UNCHECKED_CHECKED,
	WRAP_UNCHECKED_UNCHECKED,
	WRAP_UNCHECKED_ERROR,
	WRAP_ERROR_CHECKED,
	WRAP_ERROR_UNCHECKED,
	WRAP_ERROR_ERROR,
	NESTED_TRY,
	CUSTOM_HANDLER,
	CONTINUE,
	BREAK
	;
	
	@Override
 	public String toString ()
	{
		return super.toString();
	}
}
